### ISSUE TITLE
[bug] toot.cafe Instance is not recognized on the welcome screen

### ISSUE THREAD

**Issue by Fruitseller** [hyperspacedev/hyperspace#195] opened 2020-04-12 11:53 UTC
Hey,
I wanted to use hyperspace Desktop with my Mastodon Account https://toot.cafe/@Fruitsailor but I'm unable to do so.
I tried it with the full usernames `https://toot.cafe/@Fruitsailor` and `@Fruitsailor@toot.cafe` but got the error message `Instance name is invalid.`

The instance is recognized on https://instances.social/toot.cafe where you use the API from.

App Version is 1.1.0
macOS is 10.15.4

**Comment by alicerunsonfedora** [comment] 2020-04-12 14:44
I just checked our installation on https://hyperspaceapp.herokuapp.com and am unable to reproduce the issue. It appears you also have added the `@` symbol in front of your username; does using `Fruitsailor@toot.cafe` present the same issue? Using URLs and putting the extra `@` symbol in front isn't supported.

**Comment by Fruitseller** [comment] 2020-04-13 09:43
Hey, thank you for looking into my problem. I tried `Fruitsailor@toot.cafe` with hyperspace on heroku and yes I could continue. The same username on the desktop part did nothing.
When looking into which calls are being made I can see that the POST `https://toot.cafe/api/v1/apps` fails with 422 and the response `Validation failed: Redirect URI must be an absolute URI.`.

I would say something with `redirect_uris: "desktop/"` is wrong.

Hope this helps with debugging.

**Comment by alicerunsonfedora** [comment] 2020-04-13 13:30
I was able to recreate the issue on my end with the current desktop app (macOS 10.15.4, Hyperspace Desktop v1.1.0), and it seems to bug out due to a feature we introduced with auto-changing the `location` field.

Since this is an issue with the Redirect URL rather than toot.cafe not being recognized, I will close this issue and file a new one in our internal issue tracker for this particular bug.

**Closed by alicerunsonfedora** 2020-04-13 13:30 UTC

**Comment by alicerunsonfedora** [comment] 2020-04-13 13:38
I've filed an issue in out tracker. For Hyperspace Desktop team members, the issue in question is [HD-63].

**Comment by buzzworkers** [comment] 2020-04-27 10:49
Having the same problem on desktop/fedora, anything I can do to go around this ?

**Comment by alicerunsonfedora** [comment] 2020-04-27 12:29
Are you currently using the latest version (v1.1.1)? v1.1.1 should have fixed this issue.
